"""Creative image generation via Gemini API."""

import json
import os
import base64
from datetime import datetime
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
load_dotenv()  # Load .env from current directory

from .server import mcp_server
from .utils import logger

# Check for google-genai package (new unified SDK)
try:
    from google import genai
    from google.genai import types
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False
    logger.warning("google-genai package not installed. Creative generation tools will not work.")


def _get_genai_client():
    """Get configured Gemini client."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable not set")
    return genai.Client(api_key=api_key)


def _build_creative_prompt(prompt: str, offer: str, bullets: str, profits: str, cta: str) -> str:
    """Build prompt for creative generation with text overlay."""
    return f"""Создай рекламный креатив для Instagram.

ФОРМАТ: вертикальный 4:5 (1080×1350), фон на весь кадр без рамок.

СТИЛЬ И ДИЗАЙН:
{prompt}

ОБЯЗАТЕЛЬНО добавь на изображение текст:

📍 ВЕРХНЯЯ ЧАСТЬ (крупно, жирный шрифт):
"{offer}"

📍 ЦЕНТРАЛЬНАЯ ЧАСТЬ (3 буллета с маркерами):
{bullets}

📍 НИЖНЯЯ ЧАСТЬ:
Выгода: "{profits}"
Кнопка CTA: "{cta}"

ТРЕБОВАНИЯ:
- Текст ЧИТАЕМЫЙ и контрастный
- Профессиональная типографика
- Яркие цвета, привлекающие внимание
- Текст в safe zone (20-80% по вертикали)
"""


@mcp_server.tool()
async def generate_creative_image(
    prompt: str,
    offer: str,
    bullets: str,
    profits: str,
    cta: str = "Узнать больше",
    reference_image_path: Optional[str] = None,
    output_dir: Optional[str] = None
) -> str:
    """
    Generate a 4:5 Instagram creative image with text overlay via Gemini.

    Args:
        prompt: Style prompt (colors, mood, objects, background)
        offer: Main headline (6-12 words)
        bullets: 3 bullet points separated by newlines
        profits: Benefit/bonus text
        cta: Call-to-action text (default: "Узнать больше")
        reference_image_path: Optional path to reference image for style
        output_dir: Optional output directory (default: current working directory)

    Returns:
        JSON with file_path to generated image

    Example:
        generate_creative_image(
            prompt="Современный минималистичный дизайн, синий градиент",
            offer="Похудей на 10 кг за месяц",
            bullets="• Без диет\\n• Без тренировок\\n• Результат за 30 дней",
            profits="Первая консультация бесплатно",
            cta="Записаться"
        )
    """
    if not GEMINI_AVAILABLE:
        return json.dumps({
            "error": "google-generativeai package not installed. Run: pip install google-generativeai"
        }, indent=2)

    try:
        client = _get_genai_client()

        full_prompt = _build_creative_prompt(prompt, offer, bullets, profits, cta)

        # Build content parts
        contents = [full_prompt]

        # Add reference image if provided
        if reference_image_path:
            ref_path = Path(reference_image_path)
            if not ref_path.exists():
                return json.dumps({
                    "error": f"Reference image not found: {reference_image_path}"
                }, indent=2)
            ref_bytes = ref_path.read_bytes()
            ref_base64 = base64.b64encode(ref_bytes).decode()
            contents.append(types.Part.from_bytes(data=ref_bytes, mime_type="image/jpeg"))
            logger.info(f"Reference image added: {reference_image_path}")

        logger.info("Generating creative image via Gemini 3 Pro Image Preview...")

        # Use google-genai SDK with proper config
        result = await client.aio.models.generate_content(
            model="gemini-3-pro-image-preview",
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio="4:5",
                ),
                temperature=1.0,
                top_k=40,
                top_p=0.95
            )
        )

        # Extract image from response
        if not result.candidates or not result.candidates[0].content.parts:
            return json.dumps({
                "error": "No image generated by Gemini"
            }, indent=2)

        image_part = None
        for part in result.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data:
                image_part = part
                break

        if not image_part or not image_part.inline_data.data:
            return json.dumps({
                "error": "No image data in Gemini response"
            }, indent=2)

        image_bytes = image_part.inline_data.data
        if isinstance(image_bytes, str):
            image_bytes = base64.b64decode(image_bytes)

        # Determine output path
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"creative_{timestamp}.png"

        if output_dir:
            output_path = Path(output_dir) / filename
        else:
            output_path = Path.cwd() / filename

        # Ensure directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Save image (already bytes from Imagen 3)
        output_path.write_bytes(image_bytes)

        logger.info(f"Creative image saved: {output_path}")

        return json.dumps({
            "success": True,
            "file_path": str(output_path),
            "format": "4:5 (1080x1350)",
            "message": "Image generated successfully. Use Read tool to view it."
        }, indent=2)

    except Exception as e:
        logger.error(f"Error generating creative: {e}")
        return json.dumps({
            "error": str(e)
        }, indent=2)


@mcp_server.tool()
async def expand_to_stories(
    image_path: str,
    output_path: Optional[str] = None,
    upscale_4k: bool = False
) -> str:
    """
    Expand a 4:5 image to 9:16 Stories format via seamless outpainting.

    The original image content stays in the center while the background
    is extended upward and downward seamlessly.

    Args:
        image_path: Path to the 4:5 source image
        output_path: Optional path for the output (default: {original}_stories.png)
        upscale_4k: If True, generate in 4K resolution (2160x3840)

    Returns:
        JSON with file_path to expanded 9:16 image

    Example:
        expand_to_stories(image_path="/path/to/creative_20240115_143022.png", upscale_4k=True)
    """
    if not GEMINI_AVAILABLE:
        return json.dumps({
            "error": "google-generativeai package not installed. Run: pip install google-generativeai"
        }, indent=2)

    try:
        client = _get_genai_client()

        # Read source image
        source_path = Path(image_path)
        if not source_path.exists():
            return json.dumps({
                "error": f"Source image not found: {image_path}"
            }, indent=2)

        source_bytes = source_path.read_bytes()

        expand_prompt = """SEAMLESS OUTPAINTING: Extend this 4:5 image to 9:16 by continuing the background.

CRITICAL: This is OUTPAINTING - you must generate MORE of the SAME background above and below the image.

The original image has a background (gradient, color, texture, pattern, or scene).
Your job is to SEAMLESSLY CONTINUE that exact same background in the new vertical space.

REQUIREMENTS:
1. KEEP the original image EXACTLY as-is in the CENTER
2. EXTEND the background UPWARD - analyze the top edge pixels and generate matching continuation
3. EXTEND the background DOWNWARD - analyze the bottom edge pixels and generate matching continuation
4. NO VISIBLE SEAMS - the transition must be INVISIBLE, like the background was always larger
5. MATCH everything: colors, gradients, lighting, texture, blur level, grain

TECHNICAL:
- If the top has a blue gradient → continue that blue gradient upward with the same direction
- If the bottom has a blurred background → continue that same blur level
- If there's a pattern → continue the pattern seamlessly
- The edges of the original must BLEND PERFECTLY into the new areas

DO NOT:
- Move, resize, or modify ANY content from the original image
- Add new objects, text, or elements to the extended areas
- Create any visible line, border, or color shift at the original edges
- Change the original image in any way

The result should look like ONE seamless image that was always 9:16, not a 4:5 image with added borders."""

        resolution = "4K" if upscale_4k else "1080p"
        logger.info(f"Expanding image to 9:16 ({resolution}): {image_path}")

        # Build image config with optional 4K
        image_config_kwargs = {"aspect_ratio": "9:16"}
        if upscale_4k:
            image_config_kwargs["image_size"] = "4K"

        result = await client.aio.models.generate_content(
            model="gemini-3-pro-image-preview",
            contents=[
                types.Part.from_bytes(data=source_bytes, mime_type="image/png"),
                expand_prompt
            ],
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(**image_config_kwargs),
                temperature=0.2,  # Low for accurate background reproduction
                top_k=20,
                top_p=0.8
            )
        )

        # Extract image from response
        if not result.candidates or not result.candidates[0].content.parts:
            return json.dumps({
                "error": "No image generated by Gemini"
            }, indent=2)

        image_part = None
        for part in result.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data:
                image_part = part
                break

        if not image_part or not image_part.inline_data.data:
            return json.dumps({
                "error": "No image data in Gemini response"
            }, indent=2)

        expanded_bytes = image_part.inline_data.data
        if isinstance(expanded_bytes, str):
            expanded_bytes = base64.b64decode(expanded_bytes)

        # Determine output path
        if not output_path:
            suffix = "_stories_4k.png" if upscale_4k else "_stories.png"
            out_path = source_path.parent / f"{source_path.stem}{suffix}"
        else:
            out_path = Path(output_path)

        # Ensure directory exists
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # Save expanded image
        out_path.write_bytes(expanded_bytes)

        format_str = "9:16 4K (2160x3840)" if upscale_4k else "9:16 (1080x1920)"
        logger.info(f"Expanded image saved: {out_path}")

        return json.dumps({
            "success": True,
            "file_path": str(out_path),
            "format": format_str,
            "message": f"Image expanded to Stories format ({resolution}). Use Read tool to view it."
        }, indent=2)

    except Exception as e:
        logger.error(f"Error expanding image: {e}")
        return json.dumps({
            "error": str(e)
        }, indent=2)


@mcp_server.tool()
async def upscale_to_4k(
    image_path: str,
    aspect_ratio: str = "9:16",
    output_path: Optional[str] = None
) -> str:
    """
    Upscale an image to 4K resolution via Gemini.

    Takes an existing image and generates a 4K version preserving
    all details, composition and style.

    Args:
        image_path: Path to the source image
        aspect_ratio: Target aspect ratio - "9:16", "4:5", or "1:1" (default: "9:16")
        output_path: Optional path for the output (default: {original}_4k.png)

    Returns:
        JSON with file_path to 4K image

    Example:
        upscale_to_4k(image_path="/path/to/creative.png", aspect_ratio="9:16")
    """
    if not GEMINI_AVAILABLE:
        return json.dumps({
            "error": "google-generativeai package not installed. Run: pip install google-generativeai"
        }, indent=2)

    # Validate aspect ratio
    valid_ratios = ["9:16", "4:5", "1:1"]
    if aspect_ratio not in valid_ratios:
        return json.dumps({
            "error": f"Invalid aspect_ratio. Must be one of: {valid_ratios}"
        }, indent=2)

    try:
        client = _get_genai_client()

        # Read source image
        source_path = Path(image_path)
        if not source_path.exists():
            return json.dumps({
                "error": f"Source image not found: {image_path}"
            }, indent=2)

        source_bytes = source_path.read_bytes()

        upscale_prompt = """Улучши качество этого изображения до 4K разрешения.

КРИТИЧЕСКИ ВАЖНО:
- Сохрани ВСЕ детали, композицию и стиль без изменений
- Не добавляй и не убирай элементы
- Сохрани весь текст читаемым
- Улучши чёткость и детализацию
- Результат должен быть идентичен оригиналу, только в более высоком разрешении"""

        logger.info(f"Upscaling image to 4K ({aspect_ratio}): {image_path}")

        result = await client.aio.models.generate_content(
            model="gemini-3-pro-image-preview",
            contents=[
                upscale_prompt,
                types.Part.from_bytes(data=source_bytes, mime_type="image/png")
            ],
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio=aspect_ratio,
                    image_size="4K"
                ),
                temperature=0.1,  # Very low for exact reproduction
                top_k=10,
                top_p=0.8
            )
        )

        # Extract image from response
        if not result.candidates or not result.candidates[0].content.parts:
            return json.dumps({
                "error": "No image generated by Gemini"
            }, indent=2)

        image_part = None
        for part in result.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data:
                image_part = part
                break

        if not image_part or not image_part.inline_data.data:
            return json.dumps({
                "error": "No image data in Gemini response"
            }, indent=2)

        upscaled_bytes = image_part.inline_data.data
        if isinstance(upscaled_bytes, str):
            upscaled_bytes = base64.b64decode(upscaled_bytes)

        # Determine output path
        if not output_path:
            out_path = source_path.parent / f"{source_path.stem}_4k.png"
        else:
            out_path = Path(output_path)

        # Ensure directory exists
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # Save upscaled image
        out_path.write_bytes(upscaled_bytes)

        # Calculate resolution based on aspect ratio
        resolutions = {
            "9:16": "2160x3840",
            "4:5": "2160x2700",
            "1:1": "2160x2160"
        }
        res = resolutions.get(aspect_ratio, "4K")

        logger.info(f"Upscaled image saved: {out_path}")

        return json.dumps({
            "success": True,
            "file_path": str(out_path),
            "format": f"{aspect_ratio} 4K ({res})",
            "message": "Image upscaled to 4K. Use Read tool to view it."
        }, indent=2)

    except Exception as e:
        logger.error(f"Error upscaling image: {e}")
        return json.dumps({
            "error": str(e)
        }, indent=2)
